### ISSUE TITLE
option to choose model or "tier"

### ISSUE THREAD

**Issue by apolmig** [Nutlope/pdftochat#5]
great product! congrats!
just an improvement suggestion: ability to choose the model you want to use, or even a "paid" tier with superior models including vision?
awesome launch and oss ftw!

**Comment by ajaxbo360** [comment]
@apolmig good point

**Comment by VukDukic** [comment]
@apolmig I am having issues with passing data to Pinecone.  How have you set up your env variables for the Pinecone index?

**Comment by Nutlope** [comment]
Thanks @apolmig! To choose the model you want from within the app? Or as part of the code? You can already change it in the code quite easily.

I like the vision idea, might explore this in the future

**Comment by apolmig** [comment]
hi! from within the app i mean, thanks
