### ISSUE TITLE
how is this FREE as advertised by hassan on X ? when together.ai bytescale have no free tiers

### ISSUE THREAD

**Issue by fritol** [Nutlope/pdftochat#6]
how is this FREE as advertised by hassan on X ? when together.ai bytescale have no free tiers

maybe am missing something

**Comment by ajaxbo360** [comment]
@fritol soo for the together.ai you get 25$. free trial when you create an account plus you pay just for what you use.for bytescale you have 14 day trial soo yeah

**Comment by Nutlope** [comment]
@fritol the production app (pdftochat.com) is free but if you want to self host your own, it's not free.

With that said, Together.ai does provide $25 of credits, Clerk has a free tier, and Bytescale has a free trial.
